### ISSUE TITLE
borderColor not working

### ISSUE THREAD

**Issue by mweitzel2005** [GjjvdBurg/labella.py#13]
Using the following `borderColor` setting inside the `options` doct did not have any visible effect:
```
"labelBgColor":  "#fff",
"borderColor": "#000",
"labelTextColor": "#000",
```

This displayed black text on white background without any border for me. Is that expected?

**Comment by GjjvdBurg** [comment]
Sorry to hear you're having trouble. I think you need to set ``"showBorder": True``, that seems to work for me. Let me know if that solves your problem.

**Comment by mweitzel2005** [comment]
Absolutely correct, thank you! Maybe could make a nice addition to the docs.

**Comment by GjjvdBurg** [comment]
Glad to hear that works, I'll update the docs!
