### ISSUE TITLE
Gantt chart

### ISSUE THREAD

**Issue by Mcimob** [GjjvdBurg/labella.py#15]
Is there any way to make something like [this picture](https://i.pinimg.com/originals/de/c9/ed/dec9edb7a6d7e1d31a793b873c4e0c10.jpg) (events that are more than just a point) but with these nice labels?

**Comment by SeaDude** [comment]
@Mcimob , you could try Mermaid + Markdown. There is a [gantt-type chart](https://mermaid-js.github.io/mermaid/#/gantt) that could get you close.
