### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by rimjhim365** [GjjvdBurg/labella.py#2]
import error while importing TimelineTex
Already installed latex

**Comment by GjjvdBurg** [comment]
Hi @rimjhim365! Thanks for reporting this problem. I can't seem to reproduce this bug myself. Which version of Python are you using? And does "import labella" work as expected?

**Comment by rimjhim365** [comment]
@GjjvdBurg  in Python 2.7

**Comment by GjjvdBurg** [comment]
@rimjhim365 Ah, that explains it. Labella uses some features of Python that are only available in Python 3 and does not work in Python 2.7. Please try using it with Python 3.
