### ISSUE TITLE
How to convert timeline to .png?

### ISSUE THREAD

**Issue by SeaDude** [GjjvdBurg/labella.py#20]
Hello,

I'm trying to convert the .svg generated by one of the examples to .png. 

**Tried appending `THIS CODE` to the `main()` function below:**

```python
#Reference: https://stackoverflow.com/a/70357769/5976033
#!pip install cairosvg

import os
import cairosvg
from datetime import date
from labella.timeline import TimelineSVG, TimelineTex


def main():
    items = [
        {
            "time": date(1986, 1, 1), 
            "text": "Willy Wonka"
        },
        {
            "time": date(1991, 1, 1),
            "text": "Goonies",
        },
        {
            "time": date(2021, 4, 1),
            "text": "Matrix",
        }
    ]

    options = {
        "margin": {"left": 40.5, "right": 20, "top": 20, "bottom": 20},
        "initialWidth": 1600,
        "initialHeight": 1600,
        "direction": "right",
        "dotColor": "#000000",
        "labelBgColor": "#000000",
        "linkColor": "#000000",
        "textFn": lambda x: "{\\fontfamily{phv}\\selectfont" + str(x["time"].date()) + " - " + x["text"] + "}",
        "labelPadding": {"left": 2, "right": 0, "top": 0, "bottom": 0},
        "labella": {
            "nodeHeight": 22,
        },
        "latex": {"fontsize": "12pt", "reproducible": True},
    }

    tl = TimelineSVG(items, options=options)
    tl.export("timeline_kit_1.svg")

    tl = TimelineTex(items, options=options)
    tl.export("timeline_kit_1.tex")

#------------THIS CODE---------------------------
    cairosvg.svg2png(
    url="timeline_kit_1.svg", write_to="timeline_kit_1.png")

#----------------------------------------------------
if __name__ == "__main__":
    main()
```
- **But some kind of LaTeX remnant (from `textFn`?) is present on all timeline events in the resulting .png:**
    - **NOTE:**
        -  The remnants shown below are only present in the reulting .png, not the .pdf/.svg/.tex
- ![image](https://user-images.githubusercontent.com/8636973/151122729-dd3a9157-ff7e-4225-9887-2c2246abc065.png)

**Comment by SeaDude** [comment]
Hm... even trying https://svgtopng.com/ to convert the .svg to .png results in the same remnants. Its probably not with `cairosvg`. 
I'm curious to see how you do this.

**Comment by SeaDude** [comment]
Aha...leaving the `{\\fontfamily{phv}\\selectfont"` customization off of the `textfn` option seems to work. 
But, now the width of each timeline event isn't proportional to the text:
- ![image](https://user-images.githubusercontent.com/8636973/151209224-c428a331-3829-4f81-b878-8a3acee8dae7.png)

**Comment by GjjvdBurg** [comment]
It's been a while, but I probably used ImageMagick to convert directly from PDF to PNG, as this gives better results. To set custom fonts you can use the `preamble` field for the latex options.

**Comment by GjjvdBurg** [comment]
I'll close this issue as it appears to be resolved. Please reopen if that's not the case.

**Comment by SeaDude** [comment]
Right on. I spend a decent amount of time trying to install `Wand` / `ImageMagick` on Windows 10. Ew! I wasn't successful. I will try another PDF-PNG converion. 

Thank you!
