### ISSUE TITLE
How to adjust node size and font size?

### ISSUE THREAD

**Issue by SeaDude** [GjjvdBurg/labella.py#21]
Hello,

I'm having trouble adjusting `labella/nodeHeight` and `latex/fontsize` `options`. 

**Example:**

- If I set `nodeHeight` to say, 80, nothing happens to the resulting .pdf or .svg
- If I set `fontSize` to say, 18, nothing happens to the resulting .pdf or .svg either

**Options:**

```
options = {
        "margin": {"left": 70, "right": 20, "top": 20, "bottom": 20},
        "initialWidth": 1300,
        "initialHeight": 1600,
        "direction": "right",
        "dotColor": "#000000",
        "labelBgColor": "#000000",
        "linkColor": "#000000",
        "textFn": lambda x: str(x["time"].date()) + " - " + x["text"],
        "labelPadding": {"left": 2, "right": 0, "top": 2, "bottom": 0},
        "labella": {
            "nodeHeight": 30,
        },
        "latex": {"fontsize": "15pt", "reproducible": True},
    }
```

Do you have any ideas for how to control these options?

**Comment by GjjvdBurg** [comment]
The `fontsize` option is used in the `\documentclass` command in the latex document. This supports 10pt, 11pt, and 12pt. Use this to set the font size of the axis labels. To change the font of the text labels, you can use the standard latex commands (for instance `\Large`). Here's an example with `timeline_kit_1.py`:

```diff
diff --git a/examples/timeline_kit_1.py b/examples/timeline_kit_1.py
index 8ebf35f..ec760ca 100644
--- a/examples/timeline_kit_1.py
+++ b/examples/timeline_kit_1.py
@@ -51,7 +51,7 @@ def main():
         "dotColor": "#000000",
         "labelBgColor": "#000000",
         "linkColor": "#000000",
-        "textFn": lambda x: str(x["time"].year) + " - " + x["text"],
+        "textFn": lambda x: "{\Large %s -- %s}" % (x["time"].year, x["text"]),
         "labelPadding": {"left": 2, "right": 0, "top": 0, "bottom": 0},
         "labella": {
             "nodeHeight": 12,
```

**Comment by SeaDude** [comment]
That works well, thank you. 
Heres are some references for those of us new to LaTeX standard font sizes: https://latex-tutorial.com/changing-font-size/

What do you think about the `nodeHeight`? I see that they proportionally grow as the text size increases. Is it possible to make the timeline events have more real estate?

**Comment by GjjvdBurg** [comment]
The `nodeHeight` seems to be related to the distance between rows of labels (it's been a while since I wrote this package). You can however hack some more padding into the Latex labels using the ``\rule`` command, here's an example:

```diff
diff --git a/examples/timeline_kit_1.py b/examples/timeline_kit_1.py
index ba1ccaf..1b787d9 100644
--- a/examples/timeline_kit_1.py
+++ b/examples/timeline_kit_1.py
@@ -44,6 +44,9 @@ def main():
         },
     ]
 
+    textFn = (
+        lambda d: f"\\rule[-17pt]{{0pt}}{{40pt}}{d['time'].year} -- {d['text']}"
+    )
     options = {
         "margin": {"left": 40.5, "right": 20, "top": 20, "bottom": 20},
         "initialWidth": 400,
@@ -52,7 +55,7 @@ def main():
         "dotColor": "#000000",
         "labelBgColor": "#000000",
         "linkColor": "#000000",
-        "textFn": lambda x: str(x["time"].year) + " - " + x["text"],
+        "textFn": textFn,
         "labelPadding": {"left": 2, "right": 0, "top": 0, "bottom": 0},
         "labella": {
             "nodeHeight": 12,
```

Hope this helps, let's leave this issue open as a reminder to look into making this easier.

**Comment by SeaDude** [comment]
I'll try that. Take care!
