### ISSUE TITLE
OSError: [Errno 22] Invalid argument on dt2milli

### ISSUE THREAD

**Issue by adeoy** [GjjvdBurg/labella.py#4]
Hi, I had start testing your library with your examples, particularly the example 4, and everything is fine, but when I want to test my own dates it gives me the next error:

`Traceback (most recent call last):`
  `File "Timeline.py", line 56, in <module>`
    `main()`
  `File "Timeline.py", line 52, in main`
    `tl = TimelineTex(items, options=options)`
  `File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\labella\timeline.py", line 419, in __init__`
    `super().__init__(items, options=options, output_mode='tex')`
  `File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\labella\timeline.py", line 119, in __init__`
    `self.init_axis(dicts)`
  `File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\labella\timeline.py", line 161, in init_axis`
    `d3_extent(data, self.options['timeFn']))`
  `File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\labella\scale.py", line 342, in domain`
    `num_domain = list(map(dt2milli, x))`
 ` File "C:\Users\user\AppData\Local\Programs\Python\Python36-32\lib\site-packages\labella\scale.py", line 11, in <lambda>`
    **`dt2milli = lambda x : x.timestamp() * 1000.0`
`OSError: [Errno 22] Invalid argument`**

I don't know what is wrong, it only happens when I change the date of the example data. Can you please help me to solve it? Thank you!
I'm using Windows 10 x64 with Python 3.6.4 x32, also I tested with python 3.6.3 x64 but the error is still there.

**Comment by GjjvdBurg** [comment]
Hi @adeoy, thanks for checking out labella.py! Could you share the exact code you use that caused this error? Then I can test it and see if I can resolve the problem. Thanks!

**Comment by adeoy** [comment]
Hi, thanks for answering. I already solved it, or something like that haha. I switched from Windows to Ubuntu, apparently there is a bug in Python 3 on Windows with the timestamp, and when you put a date before 1970 it crashes, but in Linux its works without problems.
