### ISSUE TITLE
Width caluculation - switch to TikZ?

### ISSUE THREAD

**Issue by ashthespy** [GjjvdBurg/labella.py#5]
Just found this package - must say it makes life easier! 

For the LaTeX output, are the precompuation of the widths really required? 
i.e couldn't
```Tex
\begin{scope}[shift={(40, 3)}]
\fill[color=labelBgColorA, rounded corners=2pt]
(0, 0) rectangle (489, 16.65201) node[midway, yshift=-.75bp, anchor=center, 
           text=labelTextColorA] {\strut \textA};
\end{scope}
```
be simplified to:
```tex
\begin{scope}[shift={(40, 3)}]
\node[rectangle,text centered,anchor=north west,
           rounded corners=2pt,fill=labelBgColorA,yshift=-.75bp] at (0,0) {\strut \textA};
\end{scope}
```
This would let TikZ  figure out the width of the label, rather than having to [compute it](https://github.com/GjjvdBurg/labella.py/tree/master/docs#width-calculation)

**Comment by GjjvdBurg** [comment]
Hi! I realize this might seem counter-intuitive, and I have to admit it has been a few years since I made this package and don't exactly remember why it was added. However, I do think I added it for a reason, so I don't want to remove it unless there's an actual problem.

**Comment by ashthespy** [comment]
No real issue, I was just iterating through some colour choices and noticed it took quite a few minutes each time to build, so then looked at the code/docs and saw this intermediate step. 
Since I have used it only for a simple straight forward case so far, it seemed reasonable to let TikZ figure out the widths.  I'll probably implement something and play around a bit if need to make more timelines, but I do get your point - no need to fix what is not broken! ;-)

**Comment by GjjvdBurg** [comment]
My thoughts exactly! :)
